### ISSUE TITLE
Super agent dependency

### ISSUE THREAD

**Issue by webuniverseio** [leviwheatcroft/superagent-throttle#13]
Hi, if I understand correctly superagent is a peerDependency to throttle plugin, so would it be possible to either remove superagent dependency or move it to peerDependencies? For example enzume is used for testing react & react is a peerDependencies list: https://github.com/airbnb/enzyme/blob/master/package.json, same is with express react views:
https://github.com/reactjs/express-react-views/blob/master/package.json

I think that should be a major release since it can be potentially a breaking change for people who rely on this behavior.

Thank you.

**Comment by joelabair** [comment]
Or the dependency could simply be listed as one of the **devDependencies**.  AFICT - hard dependencies in the code only occur in 
`./example.js:2:const request       = require('superagent')`
`./test/index.js:4:import request from 'superagent'`
Neither are part of the core library.   It is, of course, possible that the code relies on some expected behavior specoific to superagent@1.8.3 - but not very likely.  This appears to simply rely on superagent's plugin support.  

The dependency on `superagent@1.8.3` or `superagent@1.8.x` is a security concern.
https://snyk.io/vuln/npm:superagent:20170807
and
https://snyk.io/vuln/npm:mime:20170907 due to the mime dependency.

In my case, manually upgrading removing superagent from the ./node_modules/superagent-throttle directory, works as a temporary solution, but is an unnecessary manual step that does not propagate well in production.

**Comment by bigman73** [comment]
The older superagent version is causing audit issues

Please upgrade superagent to the latest version

**Comment by jackellenberger** [comment]
Hi @leviwheatcroft, thanks for merging https://github.com/leviwheatcroft/superagent-throttle/pull/17, it does seem to resolve the issue. Could you build the package and push it to npm?

**Comment by leviwheatcroft** [comment]
Hi All, thanks so much for the PR, and your patience despite my egregious delay. Happy to say I've just published this to npm.
